name: Remove Domains from Textfile

on:
  push:
    paths:
      - 'phishfort_small_only_domains.txt' # Updated path to the target text file

jobs:
  remove_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Umbrella Top Million List
        run: |
          echo "Downloading Umbrella Top Million list..."
          wget -O top-1m.csv.zip https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip
          unzip -o top-1m.csv.zip -d umbrella_list
        # Save the path to the downloaded list for later steps
        env:
          UMBRELLA_LIST_PATH: umbrella_list/top-1m.csv

      - name: Read and Remove Domains from Textfile
        run: |
          echo "Removing domains from phishfort_small_only_domains.txt..."
          # Use grep to filter out domains from the target text file based on the Umbrella list
          grep -vFf "${{ env.UMBRELLA_LIST_PATH }}" phishfort_small_only_domains.txt > temp.txt && mv temp.txt phishfort_small_only_domains.txt

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Removed domains listed in top domains"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          branch: ${{ github.ref }}
