name: Update PhishFort Full Domain List

on:
  schedule:
    # Schedule the action to run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Download PhishFort domain list
      - name: Download PhishFort domain list
        run: curl -o domains.json https://raw.githubusercontent.com/phishfort/phishfort-lists/master/blacklists/domains.json      
                                  
      # Parse JSON and extract domains
      - name: Parse JSON and extract domains
        run: |
          jq -r '.[]' domains.json | sort | uniq > phishfort_full_only_domains_new.txt

      # Check if the domain list is not empty
      - name: Check if domain list is not empty
        run: |
          if [ -s phishfort_full_only_domains_new.txt ]; then
            echo "Domain list is not empty."
          else
            echo "Domain list is empty."
            exit 1
          fi

      # Count the number of domains
      - name: Count the number of domains
        run: |
          num_domains=$(wc -l < phishfort_full_only_domains_new.txt)
          echo "::set-output name=num_domains::$num_domains"

      # Add descriptions and count to output files
      - name: Add descriptions and count to output files
        run: |
          timestamp=$(date)
          num_domains=$(cat phishfort_full_only_domains_new.txt | wc -l)
          
          echo "# PhishFort Full Domain List - $timestamp" > phishfort_full_hosts.txt
          echo "# This list is formatted for use with hosts file." >> phishfort_full_hosts.txt
          echo "# It redirects listed domains to 0.0.0.0, blocking access." >> phishfort_full_hosts.txt
          echo "# Number of Entries: $num_domains" >> phishfort_full_hosts.txt
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_full_hosts.txt
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_full_hosts.txt
          echo "" >> phishfort_full_hosts.txt
          
          echo "# PhishFort Full Domain List - $timestamp" > phishfort_full_adguardhome.txt
          echo "# This list is formatted for use with AdGuard Home." >> phishfort_full_adguardhome.txt
          echo "# It blocks access to domains listed in PhishFort blacklists." >> phishfort_full_adguardhome.txt
          echo "# Number of Entries: $num_domains" >> phishfort_full_adguardhome.txt
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_full_adguardhome.txt
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_full_adguardhome.txt
          echo "" >> phishfort_full_adguardhome.txt
          
          echo "# PhishFort Full Domain List - $timestamp" > phishfort_full_only_domains.txt
          echo "# This list contains only the domain names listed in PhishFort blacklists." >> phishfort_full_only_domains.txt
          echo "# Number of Entries: $num_domains" >> phishfort_full_only_domains.txt
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_full_only_domains.txt
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_full_only_domains.txt
          echo "" >> phishfort_full_only_domains.txt
          
          echo "# PhishFort Full Domain List - $timestamp" > phishfort_full_rpz.conf
          echo "# This list is formatted for use with DNS Response Policy Zone (RPZ) servers." >> phishfort_full_rpz.conf
          echo "# It redirects listed domains to 0.0.0.0, blocking access." >> phishfort_full_rpz.conf
          echo "# Number of Entries: $num_domains" >> phishfort_full_rpz.conf
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_full_rpz.conf
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_full_rpz.conf
          echo "" >> phishfort_full_rpz.conf
          
          echo "# PhishFort Full Domain List - $timestamp" > phishfort_full_unbound.conf
          echo "# This list is formatted for use with Unbound DNS servers." >> phishfort_full_unbound.conf
          echo "# It blocks access to domains listed in PhishFort blacklists." >> phishfort_full_unbound.conf
          echo "# Number of Entries: $num_domains" >> phishfort_full_unbound.conf
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_full_unbound.conf
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_full_unbound.conf
          echo "" >> phishfort_full_unbound.conf
          
      # Generate output lists
      - name: Generate output lists
        run: |
          if [ -s phishfort_full_only_domains_new.txt ]; then
            awk '{ print "0.0.0.0", $1 }' phishfort_full_only_domains_new.txt >> phishfort_full_hosts.txt
            awk '{ print "||" $1 "^" }' phishfort_full_only_domains_new.txt >> phishfort_full_adguardhome.txt
            awk '{ print $1 }' phishfort_full_only_domains_new.txt >> phishfort_full_only_domains.txt
            awk '{ print "local-zone: \"" $1 "\" redirect\nlocal-data: \"" $1 " A 0.0.0.0\"" }' phishfort_full_only_domains_new.txt >> phishfort_full_rpz.conf
            awk '{ print "local-zone: \"" $1 "\" static\nlocal-data: \"" $1 " A 0.0.0.0\"" }' phishfort_full_only_domains_new.txt >> phishfort_full_unbound.conf
          else
            echo "Domain list is empty."
            exit 1
          fi
      
      # Check if only the timestamp line has changed
      - name: Check if only the timestamp line has changed
        id: check_timestamp_change
        run: |
          # Check if the first line has changed
          if ! diff -q <(head -n 1 phishfort_full_only_domains.txt) <(head -n 1 phishfort_full_only_domains_new.txt) &>/dev/null; then
            echo "::set-output name=changed::true"
          else
            # Check if any other line has changed
            if ! diff -q <(tail -n +2 phishfort_full_only_domains.txt) <(tail -n +2 phishfort_full_only_domains_new.txt) &>/dev/null; then
              echo "::set-output name=changed::false"
            else
              echo "::set-output name=changed::true"
            fi
          fi
      
      # Commit and push changes if the content has changed
      - name: Commit and push changes if the content has changed
        if: steps.check_timestamp_change.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add phishfort_full_hosts.txt phishfort_full_adguardhome.txt phishfort_full_only_domains.txt phishfort_full_rpz.conf phishfort_full_unbound.conf
          git diff --quiet --exit-code || git commit -m "Update PhishFort domain lists - $timestamp" && git push
