name: Update PhishFort Small Domain List 

on:
  schedule:
    # Schedule the action to run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download PhishFort domain list
        run: curl -o hotlist.json https://raw.githubusercontent.com/phishfort/phishfort-lists/master/blacklists/hotlist.json

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y parallel jq dnsutils

      - name: Parse JSON and extract valid domains
        run: |
          jq -r '.[]' hotlist.json | sort | uniq > phishfort_small_only_domains_all.txt
          > phishfort_small_only_domains_new.txt
          DNS_SERVERS=("8.8.8.8" "8.8.4.4" "1.1.1.1" "9.9.9.9" "208.67.222.222" "208.67.220.220")
          export DNS_SERVERS
          cat phishfort_small_only_domains_all.txt | parallel -j 20 '
            for dns in "${DNS_SERVERS[@]}"; do
              if dig +short @"$dns" {} > /dev/null; then
                echo {};
                break;
              fi;
            done' >> phishfort_small_only_domains_new.txt

      - name: Check if domain list is not empty
        run: |
          if [ -s phishfort_small_only_domains_new.txt ]; then
            echo "Domain list is not empty."
          else
            echo "Domain list is empty."
            exit 1
          fi

      - name: Count the number of domains
        id: count_domains
        run: |
          num_domains=$(wc -l < phishfort_small_only_domains_new.txt)
          echo "num_domains=$num_domains" >> $GITHUB_ENV

      - name: Add descriptions and count to output files
        run: |
          timestamp=$(date)
          num_domains=$(wc -l < phishfort_small_only_domains_new.txt)
          formats=("hosts" "adguardhome" "only_domains" "rpz" "unbound")

          for format in "${formats[@]}"; do
            output_file="phishfort_small_${format}.txt"
            {
              echo "# PhishFort Small Domain List - $timestamp"
              echo "# Number of Entries: $num_domains"
              echo "# Project: PhishFort (https://phishfort.com/)"
              case $format in
                hosts)
                  echo "# This list is formatted for use with hosts file."
                  echo "# It redirects listed domains to 0.0.0.0, blocking access."
                  ;;
                adguardhome)
                  echo "# This list is formatted for use with AdGuard Home."
                  echo "# It blocks access to domains listed in PhishFort blacklists."
                  ;;
                only_domains)
                  echo "# This list contains only the domain names listed in PhishFort blacklists."
                  ;;
                rpz)
                  echo "# This list is formatted for use with DNS Response Policy Zone (RPZ) servers."
                  echo "# It redirects listed domains to 0.0.0.0, blocking access."
                  ;;
                unbound)
                  echo "# This list is formatted for use with Unbound DNS servers."
                  echo "# It blocks access to domains listed in PhishFort blacklists."
                  ;;
              esac
              echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities."
              echo ""
            } > "$output_file"
          done

      - name: Generate output lists
        run: |
          awk '{ print "0.0.0.0", $1 }' phishfort_small_only_domains_new.txt >> phishfort_small_hosts.txt
          awk '{ print "||" $1 "^" }' phishfort_small_only_domains_new.txt >> phishfort_small_adguardhome.txt
          awk '{ print $1 }' phishfort_small_only_domains_new.txt >> phishfort_small_only_domains.txt
          awk '{ print "local-zone: \"" $1 "\" redirect\nlocal-data: \"" $1 " A 0.0.0.0\"" }' phishfort_small_only_domains_new.txt >> phishfort_small_rpz.conf
          awk '{ print "local-zone: \"" $1 "\" static\nlocal-data: \"" $1 " A 0.0.0.0\"" }' phishfort_small_only_domains_new.txt >> phishfort_small_unbound.conf

      - name: Check if only the timestamp line has changed
        id: check_timestamp_change
        run: |
          if diff --suppress-common-lines -q <(tail -n +2 phishfort_small_only_domains.txt) <(tail -n +2 phishfort_small_only_domains_new.txt) >/dev/null; then
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes if the content has changed
        if: env.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add phishfort_small_hosts.txt phishfort_small_adguardhome.txt phishfort_small_only_domains.txt phishfort_small_rpz.conf phishfort_small_unbound.conf
          git commit -m "Update PhishFort domain lists" && git push
