name: Update PhishFort Small Domain List

on:
  schedule:
    # Schedule the action to run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Download PhishFort domain list
      - name: Download PhishFort domain list
        run: curl -o hotlist.json https://raw.githubusercontent.com/phishfort/phishfort-lists/master/blacklists/hotlist.json

      # Parse JSON and extract domains
      - name: Parse JSON and extract domains
        run: |
          jq -r '.[]' hotlist.json | sort | uniq > phishfort_small_only_domains_new.txt

      # Check if the domain list is not empty
      - name: Check if domain list is not empty
        run: |
          if [ -s phishfort_small_only_domains_new.txt ]; then
            echo "Domain list is not empty."
          else
            echo "Domain list is empty."
            exit 1
          fi

      # Create and populate resolving_domains.txt
      - name: Create and populate resolving_domains.txt
        run: |
          awk '{ print "echo \"" $1 "\" >> resolving_domains.txt" }' phishfort_small_only_domains_new.txt | bash

      # Remove domains that do not resolve on both port 80 and 443
      - name: Remove domains that do not resolve on both port 80 and 443
        run: |
          touch resolved_domains.txt
          while IFS= read -r domain; do
            if ! timeout 1 nc -zv "$domain" 80 &>/dev/null || ! timeout 1 nc -zv "$domain" 443 &>/dev/null; then
              echo "$domain" >> resolved_domains.txt
            fi
          done < resolving_domains.txt
          
      # Count the number of domains
      - name: Count the number of domains
        run: |
          num_domains=$(wc -l < resolved_domains.txt)
          echo "::set-output name=num_domains::$num_domains"

      # Add descriptions and count to output files
      - name: Add descriptions and count to output files
        run: |
          timestamp=$(date)
          num_domains=$(cat resolved_domains.txt | wc -l)
          
          echo "# PhishFort Small Domain List - $timestamp" > phishfort_small_hosts.txt
          echo "# This list is formatted for use with hosts file." >> phishfort_small_hosts.txt
          echo "# It redirects listed domains to 0.0.0.0, blocking access." >> phishfort_small_hosts.txt
          echo "# Number of Entries: $num_domains" >> phishfort_small_hosts.txt
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_small_hosts.txt
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_small_hosts.txt
          echo "" >> phishfort_small_hosts.txt
          
          echo "# PhishFort Small Domain List - $timestamp" > phishfort_small_adguardhome.txt
          echo "# This list is formatted for use with AdGuard Home." >> phishfort_small_adguardhome.txt
          echo "# It blocks access to domains listed in PhishFort blacklists." >> phishfort_small_adguardhome.txt
          echo "# Number of Entries: $num_domains" >> phishfort_small_adguardhome.txt
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_small_adguardhome.txt
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_small_adguardhome.txt
          echo "" >> phishfort_small_adguardhome.txt
          
          echo "# PhishFort Small Domain List - $timestamp" > phishfort_small_only_domains.txt
          echo "# This list contains only the domain names listed in PhishFort blacklists." >> phishfort_small_only_domains.txt
          echo "# Number of Entries: $num_domains" >> phishfort_small_only_domains.txt
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_small_only_domains.txt
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_small_only_domains.txt
          echo "" >> phishfort_small_only_domains.txt
          
          echo "# PhishFort Small Domain List - $timestamp" > phishfort_small_rpz.conf
          echo "# This list is formatted for use with DNS Response Policy Zone (RPZ) servers." >> phishfort_small_rpz.conf
          echo "# It redirects listed domains to 0.0.0.0, blocking access." >> phishfort_small_rpz.conf
          echo "# Number of Entries: $num_domains" >> phishfort_small_rpz.conf
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_small_rpz.conf
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_small_rpz.conf
          echo "" >> phishfort_small_rpz.conf
          
          echo "# PhishFort Small Domain List - $timestamp" > phishfort_small_unbound.conf
          echo "# This list is formatted for use with Unbound DNS servers." >> phishfort_small_unbound.conf
          echo "# It blocks access to domains listed in PhishFort blacklists." >> phishfort_small_unbound.conf
          echo "# Number of Entries: $num_domains" >> phishfort_small_unbound.conf
          echo "# Project: PhishFort (https://phishfort.com/)" >> phishfort_small_unbound.conf
          echo "# This list is provided by the PhishFort project, which aims to combat phishing and malicious activities." >> phishfort_small_unbound.conf
          echo "" >> phishfort_small_unbound.conf
          
      # Generate output lists
      - name: Generate output lists
        run: |
          awk '{ print "0.0.0.0", $1 }' resolved_domains.txt >> phishfort_small_hosts.txt
          awk '{ print "||" $1 "^" }' resolved_domains.txt >> phishfort_small_adguardhome.txt
          awk '{ print $1 }' resolved_domains.txt >> phishfort_small_only_domains.txt
          awk '{ print "local-zone: \"" $1 "\" redirect\nlocal-data: \"" $1 " A 0.0.0.0\"" }' resolved_domains.txt >> phishfort_small_rpz.conf
          awk '{ print "local-zone: \"" $1 "\" static\nlocal-data: \"" $1 " A 0.0.0.0\"" }' resolved_domains.txt >> phishfort_small_unbound.conf

      # Add and commit changes
      - name: Add and commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add phishfort_small_hosts.txt phishfort_small_adguardhome.txt phishfort_small_only_domains.txt phishfort_small_rpz.conf phishfort_small_unbound.conf
          git commit -m "Update PhishFort domain lists" && git push
